In [19]:
# loading packages
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

from keras.preprocessing import image
import numpy as np


### Loading images

In [3]:
# loading and trasforming train set

train_datagen = ImageDataGenerator(rescale = 1./255,
                                  shear_range = 0.2,
                                  zoom_range = 0.2,
                                  horizontal_flip = True)
train_set = train_datagen.flow_from_directory('RockPaperScissor_Detection/rps/rps',
                                             target_size = (64, 64),
                                             batch_size = 32,
                                             class_mode = 'categorical')


Found 2520 images belonging to 3 classes.


In [11]:
# loading and transforming test set

test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('RockPaperScissor_Detection/rps-test-set/rps-test-set',
                                           target_size = (64, 64),
                                           batch_size = 32,
                                           class_mode = 'categorical')


Found 372 images belonging to 3 classes.


### Building a CNN

In [5]:
# initalize CNN
cnn = tf.keras.models.Sequential()

In [6]:
# Add Convolution layer and maxpooling layer

cnn.add(tf.keras.layers.Conv2D(filters = 32, 
                               kernel_size = 3, 
                               activation = 'relu',
                              input_shape = [64, 64, 3]))

cnn.add(tf.keras.layers.MaxPool2D(pool_size = (3, 3), strides = 2))

In [7]:
# Add second Convolution layer and maxpooling layer
cnn.add(tf.keras.layers.Conv2D(filters = 32, 
                               kernel_size = 3, 
                               activation = 'relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size = (3, 3), strides = 2))

In [8]:
# Flatten layer
cnn.add(tf.keras.layers.Flatten())

In [12]:
# Adding Full Connection
cnn.add(tf.keras.layers.Dense(units = 128, activation = 'relu'))

In [13]:
# Add output layer
cnn.add(tf.keras.layers.Dense(units = 3, activation = 'softmax'))

### Training a CNN

In [14]:
# Compile CNN
cnn.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [15]:
# training CNN and validating using test set

cnn.fit(x = train_set, validation_data = test_set, epochs = 30)


Epoch 1/30
79/79 [==============================] - 6s 72ms/step - loss: 0.6244 - accuracy: 0.7341 - val_loss: 0.3515 - val_accuracy: 0.8790
Epoch 2/30
79/79 [==============================] - 6s 71ms/step - loss: 0.1167 - accuracy: 0.9683 - val_loss: 0.2066 - val_accuracy: 0.9274
Epoch 3/30
79/79 [==============================] - 6s 71ms/step - loss: 0.0463 - accuracy: 0.9885 - val_loss: 0.2469 - val_accuracy: 0.8978
Epoch 4/30
79/79 [==============================] - 5s 69ms/step - loss: 0.0383 - accuracy: 0.9917 - val_loss: 0.4394 - val_accuracy: 0.8629
Epoch 5/30
79/79 [==============================] - 6s 69ms/step - loss: 0.0397 - accuracy: 0.9925 - val_loss: 0.6064 - val_accuracy: 0.8441
Epoch 6/30
79/79 [==============================] - 5s 64ms/step - loss: 0.0232 - accuracy: 0.9921 - val_loss: 0.3973 - val_accuracy: 0.8871
Epoch 7/30
79/79 [==============================] - 5s 64ms/step - loss: 0.0092 - accuracy: 0.9976 - val_loss: 0.3512 - val_accuracy: 0.8952
Epoch 8/30
79

### Making a single prediction

In [ ]:
class_dict = train_set.class_indices
class_dict = {v:k for k,v in class_dict.items()}
class_dict

In [62]:
test_image = image.load_img('RockPaperScissor_Detection/rps-validation/rock7.png',
                           target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
print(f"The given image shows {class_dict[np.where(result[0] == 1)[0][0]]}")
result[0]

1/1 [==============================] - 0s 11ms/step
The given image shows rock


array([0., 1., 0.], dtype=float32)

In [59]:
test_image = image.load_img('RockPaperScissor_Detection/rps-validation/paper3.png',
                           target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
print(f"The given image shows {class_dict[np.where(result[0] == 1)[0][0]]}")
result[0]

1/1 [==============================] - 0s 11ms/step
The given image shows paper


array([1., 0., 0.], dtype=float32)

In [61]:
test_image = image.load_img('RockPaperScissor_Detection/rps-validation/scissors4.png',
                           target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
print(f"The given image shows {class_dict[np.where(result[0] == 1)[0][0]]}")
result[0]

1/1 [==============================] - 0s 13ms/step
The given image shows scissors


array([0., 0., 1.], dtype=float32)