In [169]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):

    if(deriv==True):

        return x*(1-x)

    return 1/(1+np.exp(-x))

# input dataset
# X = np.array([  [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
X = np.array([  [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])

# output dataset           
y = np.array([[1,2,2,3]]).T

# seed random numbers to make calculation

# deterministic (just a good practice)
np.random.seed(1)

 
# initialize weights randomly with mean 0
# syn0 = 2*np.random.random((3,1)) - 1
syn0 = np.array([[2.0],[3.0],[1.0]])

 

for iter in range(50):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    
    # how much did we miss?
    l1_error = y - l1
    
    # multiply how much we missed by the

    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

# print("Output After Training:")
    
# print(l1)
print([1 if l >= 0.5 else 0 for l in l1])
#     break


[1, 1, 1, 1]


In [168]:
nonlin(-2.10201063+0.40321687)

0.15462287263112715

In [159]:
# syn0 = np.array([[2.0],[3.0],[1.0]])
syn0

array([[ 3.93450403],
       [ 0.40321687],
       [-2.10201063]])

In [147]:
l0 = X
l0.T

array([[0, 0, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 1, 1]])

In [148]:
np.dot(l0,syn0)

array([[1.],
       [4.],
       [3.],
       [6.]])

In [149]:
l1 = nonlin(np.dot(l0,syn0))
l1

array([[0.73105858],
       [0.98201379],
       [0.95257413],
       [0.99752738]])

In [150]:
1/(1+np.exp(0.85063774))

0.2992990941211022

In [151]:
l1_error = y - l1
l1_error

array([[-0.73105858],
       [-0.98201379],
       [ 0.04742587],
       [ 0.00247262]])

In [152]:
0.73105858 * (1 - 0.73105858)

0.19661193260838358

In [153]:
nonlin(l1,True)

array([[0.19661193],
       [0.01766271],
       [0.04517666],
       [0.00246651]])

In [154]:
0.19661193 * -0.73105858

-0.1437348383568594

In [155]:
delta  = l1_error * nonlin(l1,True)
delta

array([[-1.43734840e-01],
       [-1.73450211e-02],
       [ 2.14254253e-03],
       [ 6.09874799e-06]])

In [156]:
np.dot(l0.T,delta)

array([[ 0.00214864],
       [-0.01733892],
       [-0.15893122]])

In [157]:
syn0 += np.dot(l0.T,delta)
syn0

array([[2.00214864],
       [2.98266108],
       [0.84106878]])

In [161]:
1/(1+ np.exp(2.10201063))

0.10890155214606909

In [172]:
(110200.00 + 137800.00)/2

124000.0

In [177]:
import math

In [ ]:
p -> actuals
q -> predicted
H(p,q) = -sum(p(x)log(q(x)))

In [180]:
-(math.log(0.9) + math.log(0.9) + math.log(0.4))

1.1270117631898076

In [179]:
1* math.log(0.9)

-0.10536051565782628

In [181]:
-(math.log(0.6) + math.log(0.7) + math.log(0.1))

3.170085660698769

In [182]:
-0.04575749056 - 0.04575749056 -0.39794000867

-0.48945498979

In [183]:
-0.22184874961 -0.15490195998 -1

-1.37675070959