In [62]:
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
# load dataset
dataset = pd.read_csv('heart_failure_clinical_records_dataset.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [9]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [52]:
X[222]

array([4.20e+01, 1.00e+00, 8.60e+01, 0.00e+00, 3.50e+01, 0.00e+00,
       3.65e+05, 1.10e+00, 1.39e+02, 1.00e+00, 1.00e+00, 2.01e+02])

In [51]:
y[222]

0

In [13]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Builing an ANN

In [229]:
# Builing an ANN
ann = tf.keras.models.Sequential()

In [230]:
# Adding input layer and one hidden layer
ann.add(tf.keras.layers.Dense(units = 12, activation = 'relu'))

In [231]:
ann.add(tf.keras.layers.Dense(units = 12, activation = 'relu'))

In [232]:
# add on output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

### Training an ANN

In [233]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = [tf.keras.metrics.BinaryAccuracy(), tf.keras.metrics.FalseNegatives()])

In [234]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 350)

Epoch 1/350
8/8 [==============================] - 0s 640us/step - loss: 0.6562 - binary_accuracy: 0.6611 - false_negatives_2: 64.0000
Epoch 2/350
8/8 [==============================] - 0s 632us/step - loss: 0.6439 - binary_accuracy: 0.6778 - false_negatives_2: 64.0000
Epoch 3/350
8/8 [==============================] - 0s 579us/step - loss: 0.6327 - binary_accuracy: 0.6987 - false_negatives_2: 65.0000
Epoch 4/350
8/8 [==============================] - 0s 537us/step - loss: 0.6234 - binary_accuracy: 0.7071 - false_negatives_2: 65.0000
Epoch 5/350
8/8 [==============================] - 0s 599us/step - loss: 0.6135 - binary_accuracy: 0.7113 - false_negatives_2: 65.0000
Epoch 6/350
8/8 [==============================] - 0s 518us/step - loss: 0.6046 - binary_accuracy: 0.7113 - false_negatives_2: 65.0000
Epoch 7/350
8/8 [==============================] - 0s 442us/step - loss: 0.5956 - binary_accuracy: 0.7197 - false_negatives_2: 64.0000
Epoch 8/350
8/8 [==============================] - 0s 5

8/8 [==============================] - 0s 450us/step - loss: 0.3052 - binary_accuracy: 0.8828 - false_negatives_2: 16.0000
Epoch 62/350
8/8 [==============================] - 0s 517us/step - loss: 0.3043 - binary_accuracy: 0.8828 - false_negatives_2: 16.0000
Epoch 63/350
8/8 [==============================] - 0s 460us/step - loss: 0.3030 - binary_accuracy: 0.8787 - false_negatives_2: 16.0000
Epoch 64/350
8/8 [==============================] - 0s 553us/step - loss: 0.3018 - binary_accuracy: 0.8787 - false_negatives_2: 16.0000
Epoch 65/350
8/8 [==============================] - 0s 477us/step - loss: 0.3009 - binary_accuracy: 0.8787 - false_negatives_2: 16.0000
Epoch 66/350
8/8 [==============================] - 0s 470us/step - loss: 0.2996 - binary_accuracy: 0.8787 - false_negatives_2: 16.0000
Epoch 67/350
8/8 [==============================] - 0s 541us/step - loss: 0.2986 - binary_accuracy: 0.8828 - false_negatives_2: 15.0000
Epoch 68/350
8/8 [==============================] - 0s 508us/

8/8 [==============================] - 0s 577us/step - loss: 0.2486 - binary_accuracy: 0.8996 - false_negatives_2: 14.0000
Epoch 122/350
8/8 [==============================] - 0s 535us/step - loss: 0.2482 - binary_accuracy: 0.8996 - false_negatives_2: 14.0000
Epoch 123/350
8/8 [==============================] - 0s 461us/step - loss: 0.2470 - binary_accuracy: 0.8996 - false_negatives_2: 14.0000
Epoch 124/350
8/8 [==============================] - 0s 534us/step - loss: 0.2469 - binary_accuracy: 0.8996 - false_negatives_2: 14.0000
Epoch 125/350
8/8 [==============================] - 0s 487us/step - loss: 0.2452 - binary_accuracy: 0.8996 - false_negatives_2: 14.0000
Epoch 126/350
8/8 [==============================] - 0s 459us/step - loss: 0.2445 - binary_accuracy: 0.9038 - false_negatives_2: 13.0000
Epoch 127/350
8/8 [==============================] - 0s 515us/step - loss: 0.2434 - binary_accuracy: 0.9038 - false_negatives_2: 13.0000
Epoch 128/350
8/8 [==============================] - 0s

8/8 [==============================] - 0s 531us/step - loss: 0.2010 - binary_accuracy: 0.9205 - false_negatives_2: 10.0000
Epoch 181/350
8/8 [==============================] - 0s 455us/step - loss: 0.1999 - binary_accuracy: 0.9205 - false_negatives_2: 10.0000
Epoch 182/350
8/8 [==============================] - 0s 477us/step - loss: 0.1992 - binary_accuracy: 0.9205 - false_negatives_2: 10.0000
Epoch 183/350
8/8 [==============================] - 0s 522us/step - loss: 0.1991 - binary_accuracy: 0.9163 - false_negatives_2: 10.0000
Epoch 184/350
8/8 [==============================] - 0s 463us/step - loss: 0.1980 - binary_accuracy: 0.9205 - false_negatives_2: 10.0000
Epoch 185/350
8/8 [==============================] - 0s 465us/step - loss: 0.1967 - binary_accuracy: 0.9205 - false_negatives_2: 10.0000
Epoch 186/350
8/8 [==============================] - 0s 450us/step - loss: 0.1962 - binary_accuracy: 0.9205 - false_negatives_2: 10.0000
Epoch 187/350
8/8 [==============================] - 0s

8/8 [==============================] - 0s 504us/step - loss: 0.1577 - binary_accuracy: 0.9331 - false_negatives_2: 8.0000
Epoch 241/350
8/8 [==============================] - 0s 502us/step - loss: 0.1567 - binary_accuracy: 0.9331 - false_negatives_2: 8.0000
Epoch 242/350
8/8 [==============================] - 0s 457us/step - loss: 0.1565 - binary_accuracy: 0.9331 - false_negatives_2: 8.0000
Epoch 243/350
8/8 [==============================] - 0s 477us/step - loss: 0.1556 - binary_accuracy: 0.9372 - false_negatives_2: 8.0000
Epoch 244/350
8/8 [==============================] - 0s 467us/step - loss: 0.1545 - binary_accuracy: 0.9372 - false_negatives_2: 8.0000
Epoch 245/350
8/8 [==============================] - 0s 463us/step - loss: 0.1540 - binary_accuracy: 0.9372 - false_negatives_2: 8.0000
Epoch 246/350
8/8 [==============================] - 0s 501us/step - loss: 0.1533 - binary_accuracy: 0.9372 - false_negatives_2: 8.0000
Epoch 247/350
8/8 [==============================] - 0s 478us/

8/8 [==============================] - 0s 454us/step - loss: 0.1214 - binary_accuracy: 0.9665 - false_negatives_2: 4.0000
Epoch 301/350
8/8 [==============================] - 0s 476us/step - loss: 0.1205 - binary_accuracy: 0.9665 - false_negatives_2: 4.0000
Epoch 302/350
8/8 [==============================] - 0s 510us/step - loss: 0.1203 - binary_accuracy: 0.9665 - false_negatives_2: 4.0000
Epoch 303/350
8/8 [==============================] - 0s 416us/step - loss: 0.1199 - binary_accuracy: 0.9665 - false_negatives_2: 4.0000
Epoch 304/350
8/8 [==============================] - 0s 464us/step - loss: 0.1192 - binary_accuracy: 0.9665 - false_negatives_2: 4.0000
Epoch 305/350
8/8 [==============================] - 0s 501us/step - loss: 0.1191 - binary_accuracy: 0.9665 - false_negatives_2: 4.0000
Epoch 306/350
8/8 [==============================] - 0s 549us/step - loss: 0.1185 - binary_accuracy: 0.9665 - false_negatives_2: 4.0000
Epoch 307/350
8/8 [==============================] - 0s 464us/

### making predictions and evaluating model

In [235]:
ann.predict(sc.transform([[4.20e+01, 1.00e+00, 8.60e+01, 0.00e+00, 3.50e+01, 0.00e+00,
       3.65e+05, 1.10e+00, 1.39e+02, 1.00e+00, 1.00e+00, 2.01e+02]])) 

1/1 [==============================] - 0s 19ms/step


array([[0.0012754]], dtype=float32)

In [236]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
# print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))


2/2 [==============================] - 0s 999us/step


In [237]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[31,  6],
       [ 6, 17]])

In [238]:
accuracy_score(y_test,y_pred)

0.8

### Evaluating on train set

In [239]:
y_train_pred = ann.predict(X_train)
y_train_pred = (y_train_pred > 0.5)


8/8 [==============================] - 0s 404us/step


In [240]:
cm_train = confusion_matrix(y_train, y_train_pred)
cm_train

array([[162,   4],
       [  4,  69]])

In [241]:
accuracy_score(y_train, y_train_pred)

0.9665271966527197